using System;
using CourseExercises;
using BeecrowdExercises;

namespace Course
{
    public class Program
    {
        static void Main(string[] args)
        {
            //Course
            //Exercises.ExercicoUm();
            //Exercises.ExercicoDois();
            //Exercises.ExercicoTres();
            //Exercises.ExercicoQuatro();
            //Exercises.ExercicoCinco();
            //Exercises.ExercicioSeis();
            //Exercises.AreaDaForma();
            //Exercises.MediaIdade();
            //Exercises.MediaCondicional();
            //Exercises.MenorNumero();
            //Exercises.CobrarPlanoExtra();
            //Exercises.DiasDaSemanaCondicinal();
            //Exercises.LerVariosNumerosComWhile();
            //Exercises.CelsiusToFahrenheit();

            //Beecrowd
            //ResolvedExercises.ExercicioAreaRaio();
            //ResolvedExercises.ExercicioSoma();
            //ResolvedExercises.ExericioMultiplicacao();
            //ResolvedExercises.ExercicioSubstracao();
            //ResolvedExercises.SalarioHora();
            //ResolvedExercises.Mercadoria();
            //ResolvedExercises.ConsumoDeGasolina();
            //ResolvedExercises.DistanciaDoCarro();
            //ResolvedExercises.GasolinaGasta();
            //ResolvedExercises.Media();
            //ResolvedExercises.MediaDois();
            //ResolvedExercises.SalaryBonus();
            //ResolvedExercises.SphereVolume();
            //ResolvedExercises.Area();
            //ResolvedExercises.GreatestNumber();
            //ResolvedExercises.DistanceBetweenTwoPoints();
            //ResolvedExercises.SecondsToFullTime();
            //ResolvedExercises.BankNotes();
            //ResolvedExercises.AgeInDays();
            //ResolvedExercises.FormulaDeBhaskara();
            //ResolvedExercises.SelectionTest();
            //ResolvedExercises.Snack();
            //ResolvedExercises.Multiples();
            //ResolvedExercises.GameTime();
            //ResolvedExercises.SalaryIncrease();
            //ResolvedExercises.Interval();
            //ResolvedExercises.Average();
            //ResolvedExercises.CoordinatesOfPoint();
            //ResolvedExercises.TriangleTypes();
            //ResolvedExercises.GameTimeWithMinutes();
            //ResolvedExercises.Animal();
            //ResolvedExercises.Taxes();
            //ResolvedExercises.SimpleSort();
            //ResolvedExercises.AscendingAndDescending();
            //ResolvedExercises.FixedPassword();
            //ResolvedExercises.Quadrant();
            //ResolvedExercises.ScoreValidation();
            //ResolvedExercises.TypeOfFuel();
            //ResolvedExercises.Ages();
            //ResolvedExercises.SumOfConsecutiveEvenNumbers();
            //ResolvedExercises.SeveralScoresWithValidation();
            //ResolvedExercises.Grenais();
            //ResolvedExercises.MultiplicationTable();
            ////ResolvedExercises.SumOfConsecutiveOddNumbers();
            //ResolvedExercises.OddNumbers();
            //ResolvedExercises.IntervalPartTwo();
            //ResolvedExercises.EvenSquare();
            //ResolvedExercises.EvenOrOdd();
            //ResolvedExercises.RemainingPartTwo();
            //ResolvedExercises.WeightedAverages();
            //ResolvedExercises.HighestAndPosition();
            //ResolvedExercises.Experiments();
            //ResolvedExercises.SequenceIJPartTwo();
            //ResolvedExercises.SequenceIJPartThree();
            //ResolvedExercises.DividingXByY();
            //ResolvedExercises.MultiplesOfThirteen();
            //ResolvedExercises.RestOfDivision();
            //ResolvedExercises.PUM();
            //ResolvedExercises.SquaredAndCubic();
            //ResolvedExercises.LogicalSequence();
            //ResolvedExercises.EasyFibonacci();
            ResolvedExercises.SumOfConsecutiveOddNumbersPartTwo();
        }
    }
}